<?php

namespace FWK\Enums\RouteTypes;

use SDK\Core\Enums\Enum;

/**
 * This is the InternalAccount enumeration class.
 * This class declares enumerations for a account route type.
 * <br> This class extends SDK\Core\Enums\Enum, see this class.
 *
 * @abstract
 *
 * @see InternalAccount::LOGIN_SIMULATION
 * @see InternalAccount::LOGOUT_SIMULATION
 * @see InternalAccount::REGISTERED_USERS
 * @see InternalAccount::REGISTERED_USER_MOVE
 * @see InternalAccount::CREATE_COMPANY_DIVISION
 * @see InternalAccount::SET_COMPANY_DIVISION
 * @see InternalAccount::SALES_AGENT_CUSTOMER_ORDERS
 * @see InternalAccount::USED_ACCOUNT
 * @see InternalAccount::USED_ACCOUNT_SWITCH
 *
 * @see Enum
 *
 * @package FWK\Enums\RouteTypes
 */
abstract class InternalAccount extends Enum {
    public const ACCOUNT_REGISTERED_USER_MOVE = 'ACCOUNT_INTERNAL_ACCOUNT_REGISTERED_USER_MOVE';

    public const UPDATE_ACCOUNT = 'ACCOUNT_INTERNAL_UPDATE_ACCOUNT';

    public const SAVE_COMPANY_ROLE = 'ACCOUNT_INTERNAL_SAVE_COMPANY_ROLE';

    public const DELETE_COMPANY_ROLE = 'ACCOUNT_INTERNAL_DELETE_COMPANY_ROLE';

    public const DELETE_ACCOUNT = 'ACCOUNT_INTERNAL_DELETE_ACCOUNT';

    public const SAVE_COMPANY_DIVISION = 'ACCOUNT_INTERNAL_SAVE_COMPANY_DIVISION';

    public const APPROVE_ACCOUNT_REGISTERED_USER = 'ACCOUNT_INTERNAL_APPROVE_ACCOUNT_REGISTERED_USER';

    public const CREATE_ACCOUNT_REGISTERED_USER = 'ACCOUNT_INTERNAL_CREATE_ACCOUNT_REGISTERED_USER';

    public const DELETE_ACCOUNT_REGISTERED_USER = 'ACCOUNT_INTERNAL_DELETE_ACCOUNT_REGISTERED_USER';

    public const GET_REGISTERED_USER_EXISTS = 'ACCOUNT_INTERNAL_GET_REGISTERED_USER_EXISTS';

    public const LOGIN_SIMULATION = 'ACCOUNT_INTERNAL_LOGIN_SIMULATION';

    public const LOGOUT_SIMULATION = 'ACCOUNT_INTERNAL_LOGOUT_SIMULATION';

    public const MOVE_ACCOUNT = 'ACCOUNT_INTERNAL_MOVE_ACCOUNT';

    public const MOVE_ACCOUNT_REGISTERED_USER = 'ACCOUNT_INTERNAL_MOVE_ACCOUNT_REGISTERED_USER';

    public const ORDERS_APPROVAL_DECISION = 'ACCOUNT_INTERNAL_ORDERS_APPROVAL_DECISION';

    public const SALES_AGENT_CUSTOMER_ORDERS = 'ACCOUNT_INTERNAL_SALES_AGENT_CUSTOMER_ORDERS';

    public const SEARCH_ACCOUNT_REGISTERED_USER = 'ACCOUNT_INTERNAL_SEARCH_ACCOUNT_REGISTERED_USER';

    public const SET_COMPANY_DIVISION = 'ACCOUNT_INTERNAL_SET_COMPANY_DIVISION';

    public const UPDATE_ACCOUNT_REGISTERED_USER = 'ACCOUNT_INTERNAL_UPDATE_ACCOUNT_REGISTERED_USER';

    public const UPDATE_REGISTERED_USER = 'ACCOUNT_INTERNAL_UPDATE_REGISTERED_USER';

    public const USED_ACCOUNT = 'ACCOUNT_INTERNAL_USED_ACCOUNT';

    public const USED_ACCOUNT_SWITCH = 'ACCOUNT_INTERNAL_USED_ACCOUNT_SWITCH';
}
